FROM postgres:16

COPY scripts/create-users.sh /docker-entrypoint-initdb.d/02-create-users.sh

RUN sed -i 's/\r$//' /docker-entrypoint-initdb.d/02-create-users.sh \
    && chmod 755 /docker-entrypoint-initdb.d/02-create-users.sh
