FROM python:3.12-slim

WORKDIR /benchmark

COPY benchmark .
RUN pip install --no-cache-dir -r requirements.txt

RUN sed -i 's/\r$//' entrypoint.sh && chmod +x entrypoint.sh && mkdir -p config data reports

ENTRYPOINT ["./entrypoint.sh"]
