FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /benchmark

COPY benchmark .

RUN uv init --bare --no-cache
RUN uv add -r requirements.txt
RUN sed -i 's/\r$//' entrypoint.sh && chmod +x entrypoint.sh && mkdir -p config data reports

ENV PATH="/benchmark/.venv/bin:$PATH"

ENTRYPOINT ["./entrypoint.sh"]
