CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE inference (
    inference_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    query_id VARCHAR(100) NOT NULL,
    batch BOOLEAN NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    model_version VARCHAR(10) NOT NULL,
    designation TEXT NOT NULL,
    description TEXT,
    predicted_category VARCHAR(50) NOT NULL,
    labeled_category VARCHAR(50),
    confidence FLOAT NOT NULL,
    queried_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (user_id) REFERENCES users(user_id)
);


CREATE INDEX ix_users_username ON users (username);


INSERT INTO users (
    username,
    password_hash,
    role
)
VALUES
    ('charlie@golden-ticket.com', '$2b$12$SEW5g7rqYnl7KAznnphOKur1JUCBEBkEKyplyi8eNKASskFTyHsUq', 'user'),
    ('alice@wonderland.com', '$2b$12$zBfXsQSsdGkgSVbv1vlVd..GYknETgllr3tJwSr7CQT03JH8pi/zW', 'user'),
    ('rbanat', '$2b$12$H443cg6hZgttgptlF9UqfOxRZBiy0AdMfCry5o8kUe7Qxxnwrrgte', 'admin'),
    ('walter@white.bb', '$2b$12$83YZKlHc3bHUTe3tZyYcFOij3XaWTf6JGOqmmVbrhE.qdNIUxucM.', 'user'),
    ('mallory@jewelery.gold', '$2b$12$QK9QVgAhAuW3hCbO4ih/Rejoo3Cb7mDev4mhSJ6PjtQ6o2lSC1Mb6', 'user'),
    ('david@alabama.io', '$2b$12$up1G7i2B1QhMYycMseWMPu8qoSiVmtrSxkZrNc5GXUn2czXjuYd0S', 'user'),
    ('bkhan', '$2b$12$4la4fjepQKlzIn3AGjLK5eFQ3pY8n6ZN0PIRG.xouWqg9Uazz9s2G', 'admin'),
    ('trent@trend.tt', '$2b$12$l7Tz7Qfo4n9TCHcpPtb6weSJloNnVmjJ.dBN3uKObPDYHGEmVTo42', 'user'),
    ('rmazoyer', '$2b$12$vv5J7ngaGcqeui3PqYGWo.PECwxIQHao/2magQM1/fsl4fH.0b1/O', 'admin'),
    ('franck@osc.dub', '$2b$12$v6QJw0dJ9TZtqDlwyQEK9.EIbhQZUlS/X6ttYIKXWQXr2a4.1XC6e', 'user'),
    ('strincal', '$2b$12$EhZlmg2rHefgxI2MKH.mbOec7joigRkHp7JtimZYzIa1L7WtZxGJC', 'admin'),
    ('victor@wemby.vw', '$2b$12$1aCBhe5s7sxQKHbX1kf18OnMk0mqV.LeR3QSmaouG3wjQnkYBRljG', 'user'),
    ('eve@adam.god', '$2b$12$3G5IcVpZ52ZR.3O5aYdYQuBEA6kcK9p7Cw7VBElTJNGllrZiuFAPm', 'user'),
    ('bob@marley.fr', '$2b$12$szqBL5qqV9xFcqhWhEcZnOaHw8xTAMQsO8G7owHNhERCCF86b.E42', 'user'),
    ('admin', '$2b$12$fTfQTecrocMMykAP9FTQ/OfDZjzNKUWF1uImQFfxSE96luyQQyk..', 'admin'),
    ('marc@castlerock.me', '$2b$12$92xmPpRY0gjOAwtsrV6jle8fekTvD3JBjgq8vFCg2nGDj7ZKX7yL.', 'user'),
    ('sophie@metropolis.dc', '$2b$12$FgW4jaIFB55XSmvyf1opHeo.Q3Q4B4sy0yFPb/NVB9X33ESTwM7JG', 'user'),
    ('julien@emeraldcity.oz', '$2b$12$Ng3LVHorFLEIGNPn3acVvOFmeMYz/YXamzhIIPRltKyvRmCKRtBQO', 'user'),
    ('claire@monstropolis.ink', '$2b$12$N8Pfq380NT.vYcR4bzWd0evlrkeC4InumBRXTuqkhyWoJy9j4hdgW', 'user'),
    ('thomas@dunder-mifflin.paper', '$2b$12$hEM42aZ29oPywsJcd9jRtu0I8SKqMcrFx.fFEHDwOIngNUBIG0.ga', 'user'),
    ('laura@black-mesa.lab', '$2b$12$jjP0BnTUQgPliVQBVXtQi.z.MtkQwwDwZSOen3kk509ynViN3UrKa', 'user'),
    ('nicolas@stark.tower', '$2b$12$oqAgc1t6tIgtr4rD6jBp..MnYqEZxuHTouBTN1YxSZZ7w9JIuO1XG', 'user'),
    ('emma@arendelle.snow', '$2b$12$K4KRKtl85bQ2a4zng/ObROjTtsDUG8QQlA2kVzQ.XC75GilVFbwQi', 'user'),
    ('antoine@duckburg.money', '$2b$12$T4OekB0T.k7Rm48WZ2QG0OVstCRnxypGGqpLusbdUQg8wA5dLqNky', 'user'),
    ('lea@bikinibottom.sea', '$2b$12$jhyn4xOkBZhTeXSgLOMw6O2thvw/qya7MgYcFSWIO74yW9oGkblTC', 'user'),
    ('hugo@kanto.pkmn', '$2b$12$yDchWaowzi1n5bWwFqVpPulAsUXNdV0sAPFjqrZRBjGhObk0Pwmxa', 'user'),
    ('manon@latveria.doom', '$2b$12$A63qc.Vc//rSA1NA.nviyems3.dGfP36CMEzcZ4EQkM1K8ofMA/si', 'user'),
    ('paul@hobbiton.shire', '$2b$12$sObGiS49XnT8UtyxEimdWeNdZE/lF3//eVwtTdaHZIOpiL.P/Dd5S', 'user'),
    ('chloe@neverland.jm', '$2b$12$HEp55okcJseRDMRzhJUxVOMjh1kLpUs5mf2yMsq509/GxU79vM0Vu', 'user'),
    ('maxime@starfleet.uss', '$2b$12$OaTmsmF1OBtMTuUecLSavORWK3mUiZLcHUx3lNZh/pIskUrq7kmVe', 'user'),
    ('camille@vault-tec.wasteland', '$2b$12$7Sg1yHg/ciJ2VQoQ5KAREuMBvkJNyu4VvvfSMcg2DpkE4GLs9gJze', 'user'),
    ('louis@el-dorado.gold', '$2b$12$MWAaH/cW0wJCFnxkKnNYeevYjUOQv/w8iTiKChOY4XppDk1bQou8.', 'user'),
    ('sarah@krusty.krab', '$2b$12$iR88KHW8xw5xdg39GuqTg.oz0J9IxyEhVlsdU2LR9qSnOr6DUEM.a', 'user'),
    ('adrien@gilead.rep', '$2b$12$txAQvrg9dhZwioiaXdWTEu5.gVwipYLd6A3LHpCmCQsyWJuKuExVa', 'user'),
    ('ines@hyrule.zelda', '$2b$12$NyCuwcJu0SI7mAb9vSF/FevSz7qdSXHGf4nTirW28Lu3yeDFnh9la', 'user'),
    ('romain@aperture.science', '$2b$12$TLW6HIr5ViDtBhVhc2odcemOQ/KD8lcY.8hwu3/HiXiB02LyPg2m6', 'user'),
    ('kevin@panem.district', '$2b$12$J0E2/5mIm8bBMidOFaBT7eaJranKxq54h11poSWdzkoMMnaACEE8a', 'user'),
    ('juliette@rapture.sea', '$2b$12$GkXg.BkoPgF53Crs1mCEE.FgoBXmoDSWCrj4uGR/xW14.p1S6EBQW', 'user'),
    ('florian@atlantis.sea', '$2b$12$guXaxqQ2RHZ2RUx8kA05AeMjAaRyv9d69dvdI2w2YcRaQ.ypVN9K6', 'user'),
    ('pauline@sokovia.eu', '$2b$12$1mD9vdbUR2FYnB4pCUHea.jC6zfRmFHxCR21NhZZ0NSSu9bLQJe4q', 'user'),
    ('damien@elsinore.dk', '$2b$12$Ja5JtbsAAGFNLG65FuzpRexzMtemrotiiucyXXCXN7qrXl9DnKsn6', 'user'),
    ('celine@riverdale.cw', '$2b$12$erZQmBZuspggI3V8FcUgQeQ7UusouVZeTZLpLsWutTJCbatrgjuWC', 'user'),
    ('yann@shire.mid', '$2b$12$28smJkPpNkoEz65.XFpfLusjVtGIEFaE3aaED1urEA6E8hCFJXYcW', 'user'),
    ('margot@wutai.ff', '$2b$12$xe8l6hlkecRhs0Iwvj91GuOTXY3AALSJSkFlPginvXwyu.B2zciPa', 'user'),
    ('quentin@mordor.orc', '$2b$12$EmKQAIEF6N6R4CVP0HBOv.d04g7WoY49bsOuvmPvYF.7eBuokhpuW', 'user'),
    ('elise@themyscira.island', '$2b$12$XB597j9h3ZZif3uLnYDq.u9JVHUnFS2XmlW3G4g17ZXANUA3vh2DO', 'user'),
    ('baptiste@xavier.institute', '$2b$12$zziuPnw7mjUrEDyFg0JD2uX6..iEZoBc4eKShYkTvgZZT5Mi7ulA6', 'user'),
    ('nina@lordran.souls', '$2b$12$QdHTIa1t62w5sMOfaUBdgeEghvROI2L6zJi7NrK/MTwjg5PrieGdG', 'user'),
    ('gregoire@gravity-falls.or', '$2b$12$bAlgR5vM.PUraJ/mEyC0duaNVj/5nhG9SIgXCmoAK5ptR7lbCpxsa', 'user'),
    ('oceane@sunnydale.hell', '$2b$12$g7ydt9wKSMGRDrSczNtmKexvgqgQIzbqhaA3LJyTgYgT0BBLEX0d.', 'user'),
    ('simon@narnia.cs', '$2b$12$FZWknTHQOfMwl2A8O5MaTeIAw0QXaV.HxT6t7xwbtzyh0/vE7fcXm', 'user'),
    ('lucie@gotham.dc', '$2b$12$WP86/DfZlx0cTek3ZO4OZ..A.QATaSxMrpUC0GSogcH24ZLObMBmS', 'user'),
    ('arnaud@wonka.choc', '$2b$12$/e1Q8ietz9CGV6EUtBWoreb.BHqKtH1sQpXzelieOXddM4Z6/6kby', 'user'),
    ('valentine@arkham.gc', '$2b$12$FnIIXUhsRC8SbLSA1wR8Z.1L5oDWtfedzqDMCjzHOepze6xMj7u2W', 'user'),
    ('cedric@raccoon.city', '$2b$12$/85ARlUjZhRkkhGhQChijOntaqUITJ2cj2c6YvAGtH5VeaWTaHE86', 'user'),
    ('charlotte@genosha.mutant', '$2b$12$tUbsKW4bz06i1drIUs5J1exTPTTAaudMMVKCoaVNOD/28m4AgBfk.', 'user'),
    ('mathieu@zion.matrix', '$2b$12$6o4NmsUi2ahEflMC.A0VsOOO7223mXjn1X5I9Phr6Yray3FhiaGiO', 'user'),
    ('aurelie@olympus.gr', '$2b$12$553Ac//QT4uiV9UtQczc.edNDzX8HkkGpRz65pcgYroEOgovwugq.', 'user'),
    ('vincent@smallville.dc', '$2b$12$MbF9fwtI.6tkP/aFim1lROexEJPtBF1ZQEbZx9STliB/HIiKfH7JW', 'user'),
    ('noemie@hogwarts.wiz', '$2b$12$aKdS2q5dEA7O1MeHYsX.M.cmitbXyY1LGay3jf9ii73GarBj3NLQq', 'user'),
    ('fabien@wakanda.rw', '$2b$12$OeT2z9rsCXM/vy5y4088aupkmki2SJHU9AQG7ctxgeqGJbcoDoePO', 'user'),
    ('justine@midgar.ff', '$2b$12$jmzas/FHbvYfUIH/AInZfujw2JqM9YIsAg2rydn9g8/TUfnaIcWjy', 'user'),
    ('olivier@twinpeaks.log', '$2b$12$dXSceFpsqCynq.l2lNI6zeexrKyGKJOcb6EUkpA0YzMGoS9z/9516', 'user'),
    ('melanie@westeros.got', '$2b$12$H5S.4bqdNiCrPTvQKkjN.OQBcqvaGFahJFXqbSELcgfeVI9r4TNDq', 'user')
;
